server:
  port: 8080
spring:
  application:
    name: "auth-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
security:
  jwt:
    public: classpath:public.pem
    private: classpath:private.pem
    ttl-seconds: 3600
springdoc:
  api-docs:
    path: "/v1/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    tags-sorter: "alpha"
    operations-sorter: "alpha"
    doc-expansion: "none"
    disable-swagger-default-url: true
  packages-to-scan: "co.com.auth.api"
  paths-to-match: "/api/**"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "authentication"
    schema: "public"
    username: "postgres"
    password: "1189"
jwt:
  json-exp-roles: "/roles"
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.authentication: DEBUG